spring:
  redis:
    #配置启动redis服务的服务器ip和端口号
    host: 127.0.0.1
    port: 6779
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: q1w2e3r4
    url: jdbc:mysql://localhost:3306/boot_travel_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  #    jdbc:mysql://127.0.0.1:3306/vol_travel?characterEncoding=utf-8&useSSl=falsed
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false

server:
  servlet:
    context-path: /travel
  port: 8080
